name: Deployment Notification to Discord

on:
  deployment_status:

jobs:
  notify-discord:
    name: Notify Discord on Deployment Status
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' || github.event.deployment_status.state == 'failure'

    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          STATUS="${{ github.event.deployment_status.state }}"
          ENVIRONMENT="${{ github.event.deployment.environment }}"
          URL="${{ github.event.deployment_status.target_url }}"
          MESSAGE="🚀 Deployment $STATUS 🚀"
          EMBED_COLOR=$([ "$STATUS" == "success" ] && echo "3066993" || echo "15158332")
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\", \"embeds\": [{\"title\": \"Deployment $STATUS\", \"description\": \"**Environment**: $ENVIRONMENT\n**URL**: [Click Here]($URL)\", \"color\": $EMBED_COLOR}]}" \
               $DISCORD_WEBHOOK_URL
