name: Vercel 배포 알림을 Discord로 전송

on:
  deployment_status:

jobs:
  notify-discord:
    name: 배포 상태를 Discord로 알림
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' || github.event.deployment_status.state == 'failure'

    steps:
      - name: Discord로 알림 전송
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
         run: |
          STATUS="${{ github.event.deployment_status.state }}"
          ENVIRONMENT="${{ github.event.deployment.environment }}"
          URL="${{ github.event.deployment_status.target_url }}"
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          ACTOR="${{ github.actor }}"
          EMBED_COLOR=$([ "$STATUS" == "success" ] && echo "3066993" || echo "15158332")
          TITLE=$([ "$STATUS" == "success" ] && echo "✅ 배포 성공" || echo "❌ 배포 실패")
          THUMBNAIL_URL="https://assets.vercel.com/image/upload/front/vercel/twitter-card.png"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\", \"embeds\": [{\"title\": \"$TITLE\", \"description\": \"**환경**: $ENVIRONMENT\n**URL**: [여기를 클릭하세요]($URL)\n**배포자**: 나윱\n**배포 시간**: $TIMESTAMP\", \"color\": $EMBED_COLOR, \"thumbnail\": {\"url\": \"$THUMBNAIL_URL\"}}]}" \
               $DISCORD_WEBHOOK_URL